# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('discount', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('page', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
