# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-11 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200511_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
